server:
  port : 8080
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/credit_model?useSSL=false&allowPublicKeyRetrieval=true
    username: cmuser
    password: cmpassword
    driver-class-name: com.mysql.jdbc.Driver
    
